<?php
file_put_contents('app/Models/Komoditas.php', "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nclass Komoditas extends Model {\n    use HasFactory;\n    protected \ = 'komoditas';\n    protected \ = [];\n}\n");
file_put_contents('app/Models/HargaHarian.php', "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nclass HargaHarian extends Model {\n    use HasFactory;\n    protected \ = 'harga_harian';\n    protected \ = [];\n}\n");
file_put_contents('app/Models/Berita.php', "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nclass Berita extends Model {\n    use HasFactory;\n    protected \ = 'berita';\n    protected \ = [];\n}\n");
file_put_contents('app/Models/PantauanUser.php', "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nclass PantauanUser extends Model {\n    use HasFactory;\n    protected \ = 'pantauan_user';\n    protected \ = [];\n}\n");
file_put_contents('app/Models/RiwayatUser.php', "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nclass RiwayatUser extends Model {\n    use HasFactory;\n    protected \ = 'riwayat_user';\n    protected \ = [];\n}\n");
file_put_contents('app/Models/HasilPanen.php', "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nclass HasilPanen extends Model {\n    use HasFactory;\n    protected \ = 'hasil_panen';\n    protected \ = [];\n}\n");
file_put_contents('app/Models/ImportLog.php', "<?php\nnamespace App\Models;\nuse Illuminate\Database\Eloquent\Factories\HasFactory;\nuse Illuminate\Database\Eloquent\Model;\nclass ImportLog extends Model {\n    use HasFactory;\n    protected \ = 'import_log';\n    protected \ = [];\n}\n");
echo "SUCCESS_MODELS";
